### ISSUE TITLE
Wait background

### ISSUE THREAD

**Issue by YeJinHee** [gooormmoon/algorithm-fighter-front#71]
**_다크/라이트 전환시 다크 테마의 색이 그대로 라이트 모드에 적용됨_**

## 라이트모드

- [x] 백그라운드색 없이 경계 구분할 수 있는  border 선만 있어도 될 것 같음 (백그라운드 색 x)
- [x] border: 2px solid #e1e1e1; 하면 될 것 같음 (1px이어도 됨) (안에 다 섀도우가 있어서 따로 섀도우는 x)

## 다크모드

- [x] 경계선이 있으면 한다 해서 다크모드일 경우
`
.waitContainer {
    background: #1b2735;
` 백그라운드 색이 있어도 될 것 같음

- [x] `
.box {
        flex: 1;
        background-color: #2c3b57;
`

이 색이 있어도 상관 없을 것 같은데 내부 색이랑 아예 통일되는 게 나을 것 같음, 그게 아니라면 안에 있는 어두운 색을 크게 해서 둘 사이의 간격을 줄여도 될 것 같음

- [x] 다크모드에서 레벨 폰트 색상도 블랙이 나을 것 같음 (글자가 안 보임)

**Comment by jinjuseo** [comment]
아마 해결완료 !
